config/routes.rb
Rails.application.routes.draw do
  get "customer_info/index"
  get "customer_info/edit", to: "customer_info#edit", as: "customer_info_edit"
  post "customer_info/save", to: "customer_info#save", as: "customer_info_save"
  devise_for :customers
  get "categories/index"
  get "/categories/:id", to: "categories#show", as: "category", constraints: { id: /\d+/ }
  # get "categories/show"
  get "products/index" => "products#index", as: "products"
  # get "products/show"
  get "/products/:id", to: "products#show", as: "product", constraints: { id: /\d+/ }
  # get "products/search"
  get "/products/search/", to: "products#search", as: "products_search"

  get "about" => "about#index", as: "about"
  resources :cart, only: %i[index create destroy]
  get "cart/edit", to: "cart#edit", as: "cart_edit"
  get "cart/order_now", to: "cart#order_now", as: "cart_order_now"
  get "cart/shipping_address", to: "cart#shipping_address", as: "cart_shipping_address"
  get "cart/confirm_order", to: "cart#confirm_order", as: "cart_confirm_order"

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  scope "/application" do
    get "set_menu_state_true", to: "application#set_menu_state_true", as: "application_set_menu_state_true"
    get "set_menu_state_false", to: "application#set_menu_state_false", as: "application_set_menu_state_false"
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
  end
  def create
    product_id = params[:id].to_i
    cart_products = session[:cart]
    product_ids_array = cart_products.map { |product| product["id"] }
    unless product_ids_array.include?(product_id)
      session[:cart] << { "id": product_id, "qty": 1 }
      flash[:notice] = "Item added"
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    product_id = params[:id].to_i
    if (delete_product = session[:cart].find { |product| product["id"]==product_id })
      session[:cart].delete(delete_product)
      flash[:alert] = "Item removed"
    end
    redirect_back(fallback_location: root_path)
  end

  def edit
    product_id = params[:id].to_i
    updated_quantity = params[:quantity]
    if (edit_product = session[:cart].find { |product| product["id"]==product_id })
      session[:cart].delete(edit_product)
      session[:cart] << { "id": product_id, "qty": updated_quantity }
    end
    redirect_back(fallback_location: root_path)
  end
  def order_now
    if current_customer.present?
      address = current_customer.address
      session[:address] = address
    end
    if current_customer.present?
      if current_customer.province.present?
        province = current_customer.province
        session[:province] = province
        @gst = province.gst/100.0
        @pst = province.pst/100.0
        @hst = province.hst/100.0
      end
    end

    if session[:province].present?
      province = session[:province]
      @gst = province["gst"].to_f/100.0
      @pst = province["pst"].to_f/100.0
      @hst = province["hst"].to_f/100.0
    else
      @gst = 0.0
      @pst = 0.0
      @hst = 0.0
    end
  end

  def shipping_address
    session[:address] = params[:address]
    province = Province.find(params[:province].to_i)
    session[:province] = province

    logger.debug("Session provin is: #{session[:province]}")
    redirect_back(fallback_location: root_path)
  end

  def confirm_order
    address = session[:address]
    province = session[:province]["id"]
    total_cents = params[:total_cents]
    total_tax_rate = params[:total_tax_rate]
    @order_number = generate_unique_order_number
    customer = current_customer || Customer.find_or_create_by(email: "guest@guest.com")

    logger.debug("number: #{@order_number}, customer: #{customer}, address: #{address}, province_id: #{province}, total_cents: #{total_cents}, total_tax_rate: #{total_tax_rate}")

    order = Order.create(number: @order_number, customer: customer, address: address, province_id: province, total_cents: total_cents, total_tax_rate: total_tax_rate)

    cart.each do |product|
      if item = session[:cart].find { |cart_product| cart_product["id"]== product.id }
        OrderProduct.create(order: order, product: product, quantity: item["qty"], unit_price_cents: product.price_cents)
      end
    end
    session[:cart] = []
    session[:address] = nil
    session[:province] = nil
  end

  private
  def generate_unique_order_number
    begin
    order_number = 9.times.map { [ *0..9 ].sample }.join.to_i
    end while Order.find_by(number: order_number)
    order_number
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/checkout.html.erb
<div class="flex justify-between items-start">
    <div class="flex flex-col justify-center items-center basis-5/12">
        <h1 class="mb-2">Checkout Items</h1>
        <% @total_cents = 0 %>
        <% cart.each do |product| %>
        <div class='border-2 border-white w-full m-auto mb-5 p-4 rounded-md flex justify-center items-center'>
            <div class='basis-5/12'>
                <% if product.image.present? %>
                    <p><%= image_tag(product.image, style: 'height:150px', class:'m-auto') %></p>
                <% end %>
            </div>
            <div class='basis-7/12 text-center'>
                <h3><span class="text-red-400"><%= product.brand.name %> - <%= link_to product.name, product %></span></h3>
                <p>Unit price: <span class="text-red-400"><%= number_to_currency (product.price_cents/100.0) %></span></p>
                <% if item = session[:cart].find{ |cart_product| cart_product['id']== product.id}%>
                    <p>Quantity: <span class="text-red-400"><%= item['qty'] %></span></p>
                <% end %>
                <% @subtotal_cents = product.price_cents*item['qty'].to_i %>
                <% @total_cents += @subtotal_cents%>
                <p>Sub-total: <span class="text-red-400"><%= number_to_currency (@subtotal_cents/100.0) %></span></p>
            </div>
        </div>
        <%end%>
    </div>

    <div class="flex flex-col justify-center items-center basis-6/12">
        <h1 class="mb-2">Payment information</h1>
        <div class="border-2 border-white w-full m-auto mb-5 p-4 rounded-md flex flex-col items-start">
            
            <% if shipping_address = session[:address] %>
                <p>Address: <span class="text-red-400"><%= shipping_address %></span></p>
            <% end %>
            <% if province = session[:province] %>
                <p>Province: <span class="text-red-400"><%= province["name"] %></span></p>
            <% end %>
            <% if @gst !=0 %>
                <p>GST: <span class="text-red-400"><%= number_to_currency (@total_cents/100.0*@gst) %></span></p>
            <% end %>
            <% if @pst !=0 %>
                <p>PST: <span class="text-red-400"><%= number_to_currency (@total_cents/100.0*@pst) %></span></p>
            <% end %>
            <% if @hst !=0 %>
                <p>HST: <span class="text-red-400"><%= number_to_currency (@total_cents/100.0*@hst) %></span></p>
            <% end %>
            <p>Item(s) Sub-total: <span class="text-red-400"><%= number_to_currency (@total_cents/100.0) %></span></p>
            <p>Estimated Tax: <span class="text-red-400"><%= number_to_currency (@total_cents/100.0*(@gst+@pst+@hst)) %></span></p>
            <% @total_tax_rate = (@gst+@pst+@hst) %>
            <p>Order Total: <span class="text-red-400"><%= number_to_currency (@total_cents/100.0*(1+@gst+@pst+@hst)) %></span></p>
        </div>
        <div>
            <% if !current_customer.present? || !current_customer.province.present? %>
                <div>
                    <%= form_with(url: cart_shipping_address_path, method: :get, local: true) do |form| %>
                    <%= hidden_field_tag(:total_cents, @total_cents)%>
                    <div class="flex justify-center items-center mb-2 w-full">
                        <div class="text-black basis-3/7">
                            <%= text_field_tag(:address, nil, class: "input", placeholder: 'Shipping Address') %>
                        </div>
                        <div class="text-black basis-3/7">
                            <%= form.select :province, options_for_select(Province.all.map {|province| [province.name, province.id]}) %>
                        </div>
                        <div class="border border-gray-200 ml-1 bg-green-700 rounded-md p-2 basis-1/7">
                            <%= submit_tag("Update", class: "button is-primary") %>
                        </div>
                    </div>
                    <% end %>
                </div>
            <% end %>
            <% if province = session[:province] %>
            <div class="w-full text-center">
                <%= form_with(url: cart_order_path, method: :get, local: true) do |form| %>
                <%= hidden_field_tag(:total_cents, @total_cents)%>
                <%= hidden_field_tag(:total_tax_rate, @total_tax_rate)%>
                    <div class="hover:text-white border border-gray-200 bg-yellow-400 text-black rounded-md p-2">
                        <%= submit_tag("Confirm Order", class: "button is-primary") %>
                    </div>
                <% end %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/cart/confirm_order.html.erb
<div class="flex flex-col">
    <div class="text-center text-xl">
        <p class="mb-5">Thank you for your order!</p>
        <p class="mb-5">Your order number is <span class="text-red-400"><%= @order_number %></span></p>
        <p class="mb-5">Please proceed to the checkout process to complete your purchase!</p>
        <%= form_with url: checkout_create_path, method: :post do %>
            <%= hidden_field_tag(:order_number, @order_number)%>
            <%= button_tag "Checkout", class:"m-auto hover:bg-yellow-400 bg-yellow-500 text-white shadow-md rounded-md px-6 py-2"%>
        <% end %>
    </div>
</div>

app/views/cart/index.html.erb
<div class="flex flex-col">
    <% if session[:cart] != [] %>
        <% cart.each do |product| %>
            <div class='border border-black w-full m-auto mb-5 p-4 rounded-md flex justify-center items-center'>
                <div class='flex flex-col sm:flex-row justify-center items-center basis-1/2'>
                    <div class='basis-1/2 m-2'>
                        <% if product.image.present? %>
                            <p><%= image_tag(product.image.variant(:small_img), alt:'product image', style: 'height:130px', class:'m-auto') %></p>
                        <% end %>
                    </div>
                    <div class='basis-1/2 m-2'>
                        <p><%= product.brand.name %></p>
                        <h3><%= link_to product.name, product %></h3>
                        <% if item = session[:cart].find{ |cart_product| cart_product['id']== product.id}%>
                            <p>Quantity: <%= item['qty'] %></p>
                        <% end %>
                    </div>
                </div>
                <div class='basis-1/2 flex flex-col justify-center items-center sm:flex-row '>
                    <div class="w-full">
                    <%= form_with(url: cart_edit_path, method: :get, local: true) do |form| %>
                        <input type="hidden" name="id" id="id" value=<%= product.id %>>
                        <%= form.select :quantity, (1..100).to_a.map{|number| [number,number]}, {selected: item['qty']}, { class: "w-full mb-2" } %>
                        <%= submit_tag("Quantity Update", class: "bg-green-500 hover:bg-green-400 text-white shadow-md rounded-md p-2 text-center w-full mb-10 sm:mb-0") %>
                    <% end %>
                    </div>
                    <div class="w-full">
                        <%= button_to "Remove", cart_path(product), method: :delete , class:"bg-red-500 hover:bg-red-400 text-white shadow-md rounded-md p-2 w-full text-center sm:ml-2" %>
                    </div>
                </div>
            </div>
        <%end%>
        <p class="text-xl bg-yellow-500 hover:bg-yellow-400 text-white shadow-md w-44 rounded-md m-auto py-2 px-6 text-center">
            <%= link_to 'Order Now', cart_order_now_path %>
        </p>
    <%else%>
        <p class="text-3xl text-center"> Cart is empty. </p>
    <%end%>
</div>

app/views/cart/order.html.erb
<div class="text-center text-2xl">
<p class="mb-5">Thank you for your order!</p>
<p>Your order number is <span class="text-red-400"><%= @order_number %></span></p>
</div>

app/views/cart/order_now.html.erb
<div class="flex flex-col md:flex-row justify-between items-start">
    <div class="flex flex-col justify-center items-center w-full md:basis-5/12">
        <h1 class="montserrat text-lg underline mb-2">Checkout Items</h1>
        <% @total_cents = 0 %>
        <% cart.each do |product| %>
        <div class=' bg-slate-50 shadow-md shadow-yellow-800 w-full m-auto mb-5 p-4 rounded-md flex justify-center items-center'>
            <div class='basis-5/12'>
                <% if product.image.present? %>
                    <p><%= image_tag(product.image.variant(:small_img), alt:'product image', style: 'height:150px', class:'m-auto') %></p>
                <% end %>
            </div>
            <div class='basis-7/12 text-center'>
                <h3><span class="text-red-400"><%= product.brand.name %> - <%= link_to product.name, product %></span></h3>
                <p>Unit price: <span class="text-red-400"><%= number_to_currency (product.price_cents/100.0) %></span></p>
                <% if item = session[:cart].find{ |cart_product| cart_product['id']== product.id}%>
                    <p>Quantity: <span class="text-red-400"><%= item['qty'] %></span></p>
                <% end %>
                <% @subtotal_cents = product.price_cents*item['qty'].to_i %>
                <% @total_cents += @subtotal_cents%>
                <p>Sub-total: <span class="text-red-400"><%= number_to_currency (@subtotal_cents/100.0) %></span></p>
            </div>
        </div>
        <%end%>
    </div>

    <div class="flex flex-col justify-center items-center w-full md:basis-6/12">
        <h1 class="montserrat text-lg underline mb-2">Payment information</h1>
        <div class="bg-slate-50 shadow-md shadow-yellow-800 w-full m-auto mb-5 p-4 rounded-md flex flex-col items-start">
            <div class="mx-auto">
                <% if shipping_address = session[:address] %>
                    <p>Address: <span class="text-red-400"><%= shipping_address %></span></p>
                <% end %>
                <% if province = session[:province] %>
                    <p>Province: <span class="text-red-400"><%= province["name"] %></span></p>
                <% end %>
                <% if @gst !=0 %>
                    <p>GST: <span class="text-red-400"><%= number_to_currency (@total_cents/100.0*@gst) %></span></p>
                <% end %>
                <% if @pst !=0 %>
                    <p>PST: <span class="text-red-400"><%= number_to_currency (@total_cents/100.0*@pst) %></span></p>
                <% end %>
                <% if @hst !=0 %>
                    <p>HST: <span class="text-red-400"><%= number_to_currency (@total_cents/100.0*@hst) %></span></p>
                <% end %>
                <p>Item(s) Sub-total: <span class="text-red-400"><%= number_to_currency (@total_cents/100.0) %></span></p>
                <p>Estimated Tax: <span class="text-red-400"><%= number_to_currency (@total_cents/100.0*(@gst+@pst+@hst)) %></span></p>
                <% @total_tax_rate = (@gst+@pst+@hst) %>
                <p>Order Total: <span class="text-red-400"><%= number_to_currency (@total_cents/100.0*(1+@gst+@pst+@hst)) %></span></p>
            </div>
        </div>
        <div class="w-full">
            <% if !current_customer.present? || !current_customer.province.present? %>
                <div class="w-full">
                    <%= form_with(url: cart_shipping_address_path, method: :get, local: true) do |form| %>
                    <input type="hidden" name="total_cents" id="total_cents" value=<%= @total_cents %>>
                    <div class="flex flex-col xl:flex-row mb-2 w-full">
                        <%= text_field_tag(:address, nil, class: "input", placeholder: 'Shipping Address', class:"basis-2/3") %>
                        <%= form.select :province, options_for_select(Province.all.map {|province| [province.name, province.id]}), class:"" %>
                        <div class="xl:ml-1 bg-yellow-500 hover:bg-yellow-400 text-white shadow-md rounded-md text-center p-2 mt-3 xl:mt-0">
                            <%= submit_tag("Update", class: "button is-primary") %>
                        </div>
                    </div>
                    <% end %>
                </div>
            <% end %>
            <% if province = session[:province] %>
            <div class="w-full text-center">
                <%= form_with(url: cart_confirm_order_path, method: :get, local: true) do |form| %>
                    <input type="hidden" name="total_cents" id="confirm_order_total_cents" value=<%= @total_cents %>>
                    <input type="hidden" name="total_tax_rate" id="confirm_order_total_tax_rate" value=<%= @total_tax_rate %>>
                    <div class="hover:bg-yellow-400 bg-yellow-500 text-white shadow-md rounded-md px-6 py-2">
                        <%= submit_tag("Confirm Order", class: "button is-primary") %>
                    </div>
                <% end %>
            </div>
            <% end %>
        </div>
    </div>
</div>