config/routes.rb
Rails.application.routes.draw do
  get "customer_info/index"
  get "customer_info/edit", to: "customer_info#edit", as: "customer_info_edit"
  post "customer_info/save", to: "customer_info#save", as: "customer_info_save"
  devise_for :customers
  get "categories/index"
  get "/categories/:id", to: "categories#show", as: "category", constraints: { id: /\d+/ }
  # get "categories/show"
  get "products/index" => "products#index", as: "products"
  # get "products/show"
  get "/products/:id", to: "products#show", as: "product", constraints: { id: /\d+/ }
  # get "products/search"
  get "/products/search/", to: "products#search", as: "products_search"

  get "about" => "about#index", as: "about"
  resources :cart, only: %i[index create destroy]
  get "cart/edit", to: "cart#edit", as: "cart_edit"
  get "cart/order_now", to: "cart#order_now", as: "cart_order_now"
  get "cart/shipping_address", to: "cart#shipping_address", as: "cart_shipping_address"
  get "cart/confirm_order", to: "cart#confirm_order", as: "cart_confirm_order"

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  scope "/application" do
    get "set_menu_state_true", to: "application#set_menu_state_true", as: "application_set_menu_state_true"
    get "set_menu_state_false", to: "application#set_menu_state_false", as: "application_set_menu_state_false"
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/customer_info_controller.rb
class CustomerInfoController < ApplicationController
  def show
    @customer_info = Customer.find(params[:id])
  end

  def edit
    # @customer_info = Customer.find(params[:id].to_i)
    @customer_info = Customer.find(current_customer.id)
    @orders_history = Customer.find(current_customer.id).orders.order("created_at DESC").all
  end

  def save
    logger.debug("Address is: #{params[:address]}, Name is: #{params[:name]}, Province is: #{params[:province]}")
    # edit_customer = Customer.find(params[:id].to_i)
    edit_customer = Customer.find(current_customer.id)
    edit_customer.update(name: params[:name], address: params[:address], province_id: params[:province])
    # @customer_info.update(name: params[:name])
    # @customer_info.name = params[:name]
    # @customer_info.address = params[:address]
    # @customer_info.province = params[:province]
    # @customer_info.save
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/customer_info_helper.rb
module CustomerInfoHelper
end

app/views/customer_info/_orders_history.html.erb
<% @orders_history.each do |history_order| %>
        <div class='border border-black w-full mb-10 p-4 rounded-md'>
                <p>Order Date: <span class="text-yellow-600"><%= history_order.created_at.strftime("%d %b, %Y") %></span></p>
                <p>Order Number: <span class="text-yellow-600"><%= history_order.number %></span></p>
                <p>Order Status: <span class="text-yellow-600"><%= history_order.status %></span></p>
                <p>Order Total: <span class="text-yellow-600"><%= number_to_currency history_order.total_cents/100.0 %></span></p>
                <p class="mb-3">Total (including tax): <span class="text-yellow-600"><%= number_to_currency history_order.total_cents*(1+history_order.total_tax_rate)/100.0 %></span></p>
                <% history_order.order_products.each do |ordered_product| %>
                  <hr>
                  <div class='flex flex-col md:flex-row justify-evenly items-center my-2'>
                    <p><span class="text-yellow-600"><%= ordered_product.product.name %></span></p>
                    <p>Qty: <span class="text-yellow-600"><%= ordered_product.quantity %></span></p>
                    <p>Unit Price: <span class="text-yellow-600"><%= number_to_currency ordered_product.unit_price_cents/100.0 %></span></p>
                  </div>
                <% end %>
                <% if history_order.status == "pending" %>
                  <%= form_with url: checkout_create_path, method: :post do %>
                    
                    <input type="hidden" name="order_number" id="<%= history_order.number %>_order_number" value=<%= history_order.number %>>
                    <%= button_tag "Checkout", class:"w-full border rounded-md p-2 shadow-md bg-yellow-500 hover:bg-yellow-400 text-white"%>
                  <% end %>
                <% end %>
        </div>
      <% end %>

app/views/customer_info/edit.html.erb
<div class="flex flex-col text-base text-black justify-center items-center w-5/6 lg:w-1/2 m-auto">
    <h1 class="montserrat text-2xl mb-5">User Information</h1>
    <div class="w-full mb-10">
      <%= form_with(url: customer_info_save_path) do |form| %>
          <div class="text-black mb-3">
            <%= form.label :name, class: "" %><br>
            <%= text_field_tag(:name, @customer_info.name, class: "input w-full", placeholder: "Name") %>
          </div>

          <div class="text-black mb-5">
            <%= form.label :address, class: "" %><br>
            <div class="flex flex-col xl:flex-row">
              <%= text_field_tag(:address, @customer_info.address, class: "input", placeholder: "Address", class:"basis-2/3") %>
              <%= form.select :province, options_for_select(Province.all.map {|province| [province.name, province.id]}, @customer_info.province&.id), class:"" %>
            </div>
          </div>

          <div class="text-center">
            <%= button_tag("Update", class: "w-full border text-white text-xl rounded-md py-2 mb-3 shadow-md bg-yellow-500 hover:bg-yellow-400") %>
          </div>
      <% end %>
    </div>
    <% if @orders_history.count() > 0 %>
      <h1 class="montserrat text-2xl mb-10">You have <%= pluralize(@orders_history.count(), 'order')%></h1>
      <%= render "orders_history", collection: @orders_history %>
    <% end %>
    <div class="w-full">
      <%= button_to "Logout",destroy_customer_session_path, method: :delete, class:"w-full border text-white text-xl rounded-md py-2 mb-3 shadow-md bg-red-600 hover:bg-red-500" %>
    </div>
</div>

app/views/customer_info/index.html.erb
<div>
  <h1 class="font-bold text-4xl">CustomerInfo#index</h1>
  <p>Find me in app/views/customer_info/index.html.erb</p>
</div>

app/views/customer_info/show.html.erb
<h1><%= @customer_info.email %></h1>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
</ul>