config/routes.rb
Rails.application.routes.draw do
  get "customer_info/index"
  get "customer_info/edit", to: "customer_info#edit", as: "customer_info_edit"
  post "customer_info/save", to: "customer_info#save", as: "customer_info_save"
  devise_for :customers
  get "categories/index"
  get "/categories/:id", to: "categories#show", as: "category", constraints: { id: /\d+/ }
  # get "categories/show"
  get "products/index" => "products#index", as: "products"
  # get "products/show"
  get "/products/:id", to: "products#show", as: "product", constraints: { id: /\d+/ }
  # get "products/search"
  get "/products/search/", to: "products#search", as: "products_search"

  get "about" => "about#index", as: "about"
  resources :cart, only: %i[index create destroy]
  get "cart/edit", to: "cart#edit", as: "cart_edit"
  get "cart/order_now", to: "cart#order_now", as: "cart_order_now"
  get "cart/shipping_address", to: "cart#shipping_address", as: "cart_shipping_address"
  get "cart/confirm_order", to: "cart#confirm_order", as: "cart_confirm_order"

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  scope "/application" do
    get "set_menu_state_true", to: "application#set_menu_state_true", as: "application_set_menu_state_true"
    get "set_menu_state_false", to: "application#set_menu_state_false", as: "application_set_menu_state_false"
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/_footer.html.erb
<footer class="text-yellow-500">
  <div class="bg-gradient-to-r from-gray-800 to-gray-900 flex flex-wrap w-full items-center justify-between mx-auto px-0 md:px-20 py-8 text-xl">
    <div class="text-lg px-8 py-4">
        <p class="mb-5">Phone: <%= @main_store_contact.phone %></p>
        <p class="mb-5">E-mail: <%= @main_store_contact.email %></p>
        <p >Address: <%= @main_store_contact.location %></p>
    </div>
    <div class="text-lg px-8 py-4">
        <p>Open hours:</p>
        <p class="">Mon: <%= @main_store_contact.open_mon %></p>
        <p class="">Tue: <%= @main_store_contact.open_tue %></p>
        <p class="">Wed: <%= @main_store_contact.open_wed %></p>
        <p class="">Thu: <%= @main_store_contact.open_thu %></p>
        <p class="">Fri: <%= @main_store_contact.open_fri %></p>
        <p class="">Sat: <%= @main_store_contact.open_sat %></p>
        <p class="">Sun: <%= @main_store_contact.open_sun %></p>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <title>Camera Store</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gabarito&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-black bg-white h-screen flex flex-col justify-between">
    <header>
      <nav class="montserrat">
        <% @menu_show = false %>
        <div class="bg-gradient-to-r from-yellow-400 to-yellow-500 flex flex-wrap items-center justify-between mx-auto px-4 text-lg">
          <div class="basis-1/3 sm:hidden">
            <% if session[:menu_state] == false %>
              <%= link_to icon("bars-3", class:"size-9 hover:text-gray-500 border-2 border-black rounded-md p-1"), application_set_menu_state_true_path %>
            <% else %>
              <%= link_to icon("x-mark", class:"size-9 hover:text-gray-500 border-2 border-black rounded-md p-1"), application_set_menu_state_false_path %>
            <% end %>
          </div>
          <div class="basis-1/3 sm:basis-1/4 sm:flex justify-start items-center">
            <%= link_to image_tag( "WBCLogo.png", alt: "Company Logo", class:"size-12 mx-auto"), root_path, class:"text-base"  %>
            <p class="hidden lg:block"><%= link_to 'Winnipeg Best Camera', root_path, class:"text-base" %></p>
          </div>
          <div class="hidden sm:block">
            <ul class="flex flex-row space-x-8 mr-2">
              <li class="hover:text-gray-500 hover:font-semibold"><%= link_to 'Home', root_path %></li>
              <li class="hover:text-gray-500 hover:font-semibold"><%= link_to 'Products', products_path %></li>
              <li class="hover:text-gray-500 hover:font-semibold"><%= link_to 'About', about_path %></li>
            </ul>
          </div>

          <div class="basis-1/3 sm:basis-1/4 flex justify-end items-center">
            <% if current_customer != nil %>
                <p class="hidden sm:block">Hi, <%= current_customer.name %></p>
                <p><%= link_to icon("user-circle", class:"size-7 hover:text-gray-500 ml-2"), customer_info_edit_path(:id => current_customer.id) %></p>
            <% else %>
                <p><%= link_to icon("user-circle", class:"size-7 hover:text-gray-500"), new_customer_session_path, class:"" %></p>
            <% end %>

            <%= link_to icon("shopping-cart", class:"size-7 hover:text-gray-500 ml-2") , cart_index_path, class:"" %><%if cart.length()>0%> <p>(<%= cart.length() %>)</p> <%end%>
          </div>
        </div>
        
        <% logger.debug("Menu state is: #{session[:menu_state]}")%>
        <% if session[:menu_state] == true %>
        <div class="sm:hidden" id="mobile-menu">
          <div class="space-y-1 px-2 pb-3 pt-2 bg-slate-200">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <p class="block rounded-md px-3 py-2 text-base font-medium text-black hover:bg-yellow-100 hover:text-blue-800"><%= link_to 'Home', root_path %></a>
            <p class="block rounded-md px-3 py-2 text-base font-medium text-black hover:bg-yellow-100 hover:text-blue-800"><%= link_to 'Products', products_path %></a>
            <p class="block rounded-md px-3 py-2 text-base font-medium text-black hover:bg-yellow-100 hover:text-blue-800"><%= link_to 'About', about_path %></a>
            <p class="block rounded-md px-3 py-2 text-base font-medium text-black hover:bg-yellow-100 hover:text-blue-800"><%= link_to 'Cart', cart_index_path %></a>
          </div>
        </div>
        <% end %>

      </nav>

      <% flash.each do |type, msg| %>
        <% if type == 'notice' %>
          <div class="flex items-center px-4 py-2 mb-4 text-sm text-green-800 border border-green-300 rounded-lg bg-green-50">
        <% else %>
          <div class="flex items-center px-4 py-2 mb-4 text-sm text-red-800 border border-red-300 rounded-lg bg-red-50">
        <% end %>    
            <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
              <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
            </svg>
            <%= msg %>
          </div>
      <% end %>

    </header>
    <main class="container mx-auto my-8 px-5 flex flex-col justify-center">
      <%= yield %>
    </main>
    <%= render "/layouts/footer" %>
  </body>
  
</html>